### ISSUE TITLE
Faced `cannot load such file -- ractor/tvar/ractor_tvar.so (LoadError)` after bundle install and bundle exec

### ISSUE THREAD

**Issue by yoshitsugu** [ko1/ractor_tvar#1]
- Gemfile
```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

gem 'ractor-tvar'
```

- sample.rb
same as README
```ruby
require 'ractor/tvar'

tv = Ractor::TVar.new(0)

N = 10_000

r = Ractor.new tv do |tv|
  N.times do
    Ractor.atomically do
      tv.value += 1
    end
   end
end

N.times do
  Ractor.atomically do
    tv.value += 1
  end
end

r.take # wait for the ractor

p tv.value #=> 20000 (= N * 2)
```

```
$ bundle install
$ bundle exec ruby sample.rb
(...)/ractor-tvar-0.1.0/lib/ractor/tvar.rb:4:in `require': cannot load such file -- ractor/tvar/ractor_tvar.so (LoadError)
        from (...)/ractor-tvar-0.1.0/lib/ractor/tvar.rb:4:in `<top (required)>'
        from sample.rb:1:in `require'
        from sample.rb:1:in `<main>'
```

If I place `ractor_tvar.so` to correct path manually, it works fine.
Do you have any idea for this problem?

**Comment by ko1** [comment]
Thank you for reporting.

0.2.0 (3907cfac4b91b8e656ada8cb2491af54439a27ce) solved it. maybe.

**Comment by yoshitsugu** [comment]
Now it works fine. Thank yout very much!
