### ISSUE TITLE
Compatible with most recent Ruby?

### ISSUE THREAD

**Issue by chrisseaton** [ko1/ractor_tvar#2]
When I rest against `master` I get

```
<internal:ractor>:38: warning: Ractor is experimental, and the behavior may change in future versions of Ruby! Also there are many implementation issues.
#<Thread:0x00007ff4b8936958 run> terminated with exception (report_on_exception is true):
#<Thread:0x00007ff4a0897d20 run> terminated with exception (report_on_exception is true):
/Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `atomically': #<Thread:0x00007ff4a0897690 run> terminated with exception (report_on_exception is true):
/Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `atomically'#<Thread:0x00007ff4a08979d8 run> terminated with exception (report_on_exception is true):
ractor unsafe method called from not main ractor: ractor unsafe method called from not main ractor (Ractor::UnsafeError)
 (Ractor::UnsafeError)/Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `atomically'
: ractor unsafe method called from not main ractor (Ractor::UnsafeError	from /Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `block (4 levels) in <class:TVarTest>'
)
	from /Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `block (4 levels) in <class:TVarTest>'
	from /Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `times'
	from /Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `block (4 levels) in <class:TVarTest>'
	from /Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `block (3 levels) in <class:TVarTest>'
	from /Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `times'
	from /Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `times'
	from /Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `block (3 levels) in <class:TVarTest>'
	from /Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `block (3 levels) in <class:TVarTest>'
/Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `atomically': ractor unsafe method called from not main ractor (Ractor::UnsafeError)
	from /Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `block (4 levels) in <class:TVarTest>'
	from /Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `times'
	from /Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:70:in `block (3 levels) in <class:TVarTest>'
E
====================================================================================================================================================================================================================================================================================================
/Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:73:in `block in <class:TVarTest>'
/Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:73:in `each'
/Users/chrisseaton/src/github.com/ko1/ractor-tvar/test/ractor/tvar_test.rb:73:in `block (2 levels) in <class:TVarTest>'
<internal:ractor>:132:in `take'
Error: test: Ractor::TVar consistes with other Ractors(Ractor::TVarTest): Ractor::RemoteError: thrown by remote Ractor.
====================================================================================================================================================================================================================================================================================================

```

I also can't run your demo app

```ruby
require 'ractor/tvar'

tv = Ractor::TVar.new(0)

N = 10_000

r = Ractor.new tv do |tv|
  N.times do
    Ractor.atomically do
      tv.value += 1
    end
   end
end

N.times do
  Ractor.atomically do
    tv.value += 1
  end
end

r.take # wait for the ractor

p tv.value #=> 20000 (= N * 2)
```

```
% bundle exec ruby test.rb
<internal:ractor>:38: warning: Ractor is experimental, and the behavior may change in future versions of Ruby! Also there are many implementation issues.
#<Thread:0x00007f7ef606ff50 run> terminated with exception (report_on_exception is true):
test.rb:9:in `atomically': ractor unsafe method called from not main ractor (Ractor::UnsafeError)
	from test.rb:9:in `block (2 levels) in <main>'
	from test.rb:8:in `times'
	from test.rb:8:in `block in <main>'
<internal:ractor>:132:in `take': thrown by remote Ractor. (Ractor::RemoteError)
	from test.rb:21:in `<main>'
test.rb:9:in `atomically': ractor unsafe method called from not main ractor (Ractor::UnsafeError)
	from test.rb:9:in `block (2 levels) in <main>'
	from test.rb:8:in `times'
	from test.rb:8:in `block in <main>'
```

It looks like you can't call `atomically` from a `Ractor`?

**Comment by ko1** [comment]
Thank you! I missed your issue and v0.4.0 fixed it.
